# Generated by Django 5.1.1 on 2024-12-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='posts_pic')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('content_type', models.CharField(choices=[('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Food', 'Food'), ('Gym', 'Gym')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
