# Generated by Django 5.1.1 on 2024-12-08 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Sports', 'Sports')], max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postsmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.CharField(choices=[('Images', 'Images'), ('Videos', 'Videsos')], max_length=100)),
                ('file', models.FileField(upload_to='files')),
                ('Posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.posts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
