# Generated by Django 5.1.1 on 2024-12-08 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='media/default_image.jpg', upload_to='files'),
        ),
        migrations.AddField(
            model_name='posts',
            name='media',
            field=models.CharField(choices=[('Images', 'Images'), ('Videos', 'Videsos')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Postsmedia',
        ),
    ]
