# Generated by Django 5.1.1 on 2024-12-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_posts_media_remove_posts_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_profile',
        ),
    ]
